# all ids for grid world game
GRID_WORLD_ACTIONS = "grid_world_mouse_button"
GRID_WORLD_GAMEFIELS = "grid-world-heatmap"
GRID_WORLD_UPDATE_BUTTON = "grid-world-update-button"
GRID_WORLD_TEXT_BOX = "grid-world-text-box"
GRID_WORLD_ACTION_VALUE = "grid-world-action-dropdown-value"
GRID_WORLD_START_TRAINING_BUTTON = "grid-world-start-training-button"
GRID_WORLD_START_TRAINED_AGENT_BUTTON = "grid-world-start-trained-agent-button"
GRID_WORLD_TRAINED_AGENT_VALUE = "grid-world-trained-agent-dropdown-value"
GRID_WORLD_GAMEFIELS_TRAINED_AGENT = "grid-world-heatmap-trained-agent"
GRID_WORLD_TEXT_BOX_TRAINED_AGENT = "grid-world-text-box-trained-agent"
GRID_WORLD_PLACEHOLDER = "grid-world-placeholder"